# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/richa/gitrepo/RC2014_fpga/zedboard/RC2014_fpga/RC2014_fpga.srcs/sources_1/ip/R0001009/R0001009.xci
# IP: The module: 'R0001009' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/richa/gitrepo/RC2014_fpga/zedboard/RC2014_fpga/RC2014_fpga.srcs/sources_1/ip/R0001009/R0001009_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'R0001009'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/richa/gitrepo/RC2014_fpga/zedboard/RC2014_fpga/RC2014_fpga.srcs/sources_1/ip/R0001009/R0001009.xci
# IP: The module: 'R0001009' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/richa/gitrepo/RC2014_fpga/zedboard/RC2014_fpga/RC2014_fpga.srcs/sources_1/ip/R0001009/R0001009_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'R0001009'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
