# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/RC2014_fpga.xdc

# IP: ip/CPM_BASIC/CPM_BASIC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPM_BASIC || ORIG_REF_NAME==CPM_BASIC} -quiet] -quiet

# IP: ip/SCM_V100_S3_SCS3_32K/SCM_V100_S3_SCS3_32K.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCM_V100_S3_SCS3_32K || ORIG_REF_NAME==SCM_V100_S3_SCS3_32K} -quiet] -quiet
